parameters:
  - name: script_parameter
    type: string

steps:
  - task: AzureCLI@2
    name: submit_aml_job_task
    displayName: Execute Azure ML pipeline job
    continueOnError: false
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        ${{parameters.script_parameter}}
