pr: none
trigger: none
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_infra_dev_vg

# parameters:
#  - name: env_name
#    displayName: "Execution Environment"
#    default: "infra"

stages:
  - template: ../../../templates/platform_infra_bicep_pipeline.yml
  # - template: ../../templates/variables_template_infra.yml
    # parameters:
      # env_name: ${{parameters.env_name}}

    # parameters:
    #   environmentName: $(ENVIRONMENT)
    #   azureMgrConnection: $(AZURE_RM_SVC_CONNECTION)
    #   resourceGroup: $(RESOURCE_GROUP_NAME)
    #   location: $(LOCATION)
    #   storageAccount: $(STORAGEACCOUNT)
    #   keyVaultName: $(KEYVAULT_NAME)
    #   appInsightsName: $(APPINSIGHTS)
    #   containerRegistryName: $(REGISTRY_NAME)
    #   amlWorkspaceName: $(WORKSPACE_NAME)
    #   clusterName: $(CLUSTER_NAME)
    #   clusterSize: $(CLUSTER_SIZE)
    #   batchClusterName: $(BATCH_CLUSTER_NAME)

