pr: none
trigger:
  branches:
   include:
     - master
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/nyc_taxi/*
      - src/nyc_src/*
      - model/nyc_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg
- name: PIPELINE_TYPE
  value: nyc_taxi

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"
   default: "nyc_taxi"
 - name: is_batch_deployment
   displayName: "determine real or batch deployment"

stages:
  - template: templates/variables_template.yml
    parameters:
      env_name: ${{parameters.env_name}}
      model_type: ${{parameters.model_type}}
  - template: platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      is_batch_deployment: ${{ parameters.is_batch_deployment }}