# Azure ML configuration.
aml_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}

environment_configuration:
  env_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  build_reference: ${BUILD_BUILDID}

pipeline_configs:
  london_taxi_pr: 
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/london_taxi/environment/conda.yml
    aml_env_name: london_env
    dataset_name: london_taxi_pr_data       

  nyc_taxi_pr: 
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/nyc_taxi/environment/conda.yml
    aml_env_name: nyc_env
    dataset_name: london_taxi_pr_data

  london_taxi_dev: 
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/london_taxi/environment/conda.yml
    aml_env_name: london_env
    dataset_name: london_taxi_pr_data       

  nyc_taxi_dev: 
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/nyc_taxi/environment/conda.yml
    aml_env_name: nyc_env
    dataset_name: london_taxi_pr_data

deployment_configs:
    london_taxi_batch_dev: 
      score_file_name: score.py
      score_dir: model/london_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/london_taxi/batch_environment/conda.yml
      endpoint_name: london-taxi-be-005
      endpoint_desc: A batch endpoint serving an MLflow model for online taxi
      deployment_name: london-taxi-bd-005
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 300
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment
      test_dataset_name: london_taxi_batch_test
    
    london_taxi_online_dev:
      score_file_name: score.py
      test_file_path: model/london_taxi/online_test_data/sample-request.json
      endpoint_name: london-taxi-rte-005
      endpoint_desc: An online endpoint serving an MLflow model for online taxi
      deployment_desc: 
      deployment_name: london-taxi-rtd-005
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/london_taxi/online_environment/conda.yml
      score_dir: model/london_taxi/online
      deployment_instance_count: 1
      
    nyc_taxi_batch_dev:
      score_file_name: score.py
      score_dir: model/nyc_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/nyc_taxi/batch_environment/conda.yml
      endpoint_name: nyc-taxi-be-005
      endpoint_desc: A batch endpoint serving an MLflow model for online taxi
      deployment_name: nyc-taxi-bd-005
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 300
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment
      test_dataset_name: london_taxi_batch_test
    
    nyc_taxi_online_dev:
      score_file_name: score.py
      test_file_path: model/nyc_taxi/online_test_data/sample-request.json
      endpoint_name: nyc-taxi-rte-005
      endpoint_desc: An online endpoint serving an MLflow model for online taxi
      deployment_desc: 
      deployment_name: nyc-taxi-rtd-005
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/nyc_taxi/online_environment/conda.yml
      score_dir: model/nyc_taxi/online
      deployment_instance_count: 1
