trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/docker_taxi/*
      - src/docker_taxi_src/*
      - model/docker_taxi/*
      - src/shared/*
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "model type"
   default: "docker_taxi"
 - name: is_docker
   displayName: "Is Docker used for build validation?"
   type: boolean
   default: true

stages:
  - template: templates/platform_pr_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      is_docker: ${{ parameters.is_docker }}