pr: none
trigger:
  branches:
   include:
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/nyc_taxi/*
      - src/nyc_src/*
      - model/nyc_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "model type"
   default: "nyc_taxi"
 - name: is_batch_deployment
   displayName: "True for batch endpoint and False for real-time endpoint"

stages:
  - template: templates/platform_ci_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      is_batch_deployment: ${{ parameters.is_batch_deployment }}