trigger: none
pr: none
  
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

stages:
- stage: register_datasets
  displayName: register_datasets_stage
  jobs:
  - job: Execute_dataset_registration
    steps:
    - template: configure_azureml_agent.yml
    - template: templates/execute_python_code.yml
      parameters:
        step_name: "Register Dataset"
        script_parameter: |
          python -m mlops.common.register_data_asset.py \
            --data_config_path config/data_config.json