name: Cleanup Registered Models

on:
  workflow_dispatch:
    inputs:
      date:
        type: string
        description: "delete date e.g YYYY-MM-DD"
        default: '2024-08-14'
        required: true
      jobType:
        type: choice
        description: "Type of the job to be run"
        default: 'getModelArtifacts'
        required: true
        options:
          - 'getModelArtifacts'
          - 'deleteModelArtifacts'
env:
  CLEAN_UP_DATE: ${{ inputs.date }}
  JOB_TYPE: ${{ inputs.jobType }}
  PYTHON_VERSION: "3.9"
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
  ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}
  BUILD_BUILDID: ${{ github.run_id }}
  BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write
  contents: read
jobs:
  cleanup-registered-models:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, X64]
    defaults:
      run:
        shell: bash
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Configure Azure ML Agent
        run: python -m pip install --upgrade -r .github/requirements/execute_job_requirements.txt

      - name: Get Model Artifacts
        if: env.JOB_TYPE == 'getModelArtifacts'
        run: |
          python -m mlops.common.get_registered_models \
            --clean_up_date ${{ env.CLEAN_UP_DATE }}

      - name: Delete Registered Models
        if: env.JOB_TYPE == 'deleteModelArtifacts'
        run: |
          python -m mlops.common.delete_registered_models \
            --clean_up_date ${{ env.CLEAN_UP_DATE }}
            