name: ModelFactory-Bicep-Deployment
on:
  workflow_dispatch:
env:
  APPINSIGHTS_NAME: ${{ vars.APPINSIGHTS_NAME }}
  AZURE_RM_SVC_CONNECTION: ${{ vars.AZURE_RM_SVC_CONNECTION }}
  CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
  KEYVAULT_NAME: ${{ vars.KEYVAULT_NAME }}
  LOCATION: ${{ vars.LOCATION }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  STORAGE_ACCT_NAME: ${{ vars.STORAGE_ACCT_NAME }}
  WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
  ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}
  SUBSCRIPTION_ID: ${{vars.SUBSCRIPTION_ID}}
jobs:
  run-infra-provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Display parameters
        run: |
          echo 'See the contents of parameters passed in'
          echo $APPINSIGHTS_NAME
          echo $AZURE_RM_SVC_CONNECTION
          echo $CONTAINER_REGISTRY_NAME
          echo $KEYVAULT_NAME
          echo $LOCATION
          echo $RESOURCE_GROUP_NAME
          echo $STORAGE_ACCT_NAME
          echo $WORKSPACE_NAME
          echo ${{ github.workspace }}
          echo $ARM_CLIENT_ID
          echo $ARM_TENANT_ID
          echo $SUBSCRIPTION_ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}         
          
      - name: Provision AzureML Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az --version
            az deployment sub create --location=$LOCATION \
            --template-file '${{ github.workspace }}/infra/bicep/public_workspace/main.bicep' \
            --parameters resourceGroupName=$RESOURCE_GROUP_NAME location=$LOCATION \
            storageAccount=$STORAGE_ACCT_NAME \
            keyVaultName=$KEYVAULT_NAME \
            appInsightsName=$APPINSIGHTS_NAME \
            containerRegistryName=$CONTAINER_REGISTRY_NAME \
            amlWorkspaceName=$WORKSPACE_NAME
