name: London Taxi PR Workflow

on:
  pull_request:
    branches:
      - development
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/london_taxi/**'
      - 'model/london_taxi/**'
      - 'src/london_src/**'
      - 'test/london_taxi/**'
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "london_taxi"
permissions:
  id-token: write
  contents: read    
env:
  SUBSCRIPTION_ID: ${{vars.SUBSCRIPTION_ID}}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
  ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}
  BUILD_BUILDID: ${{ github.run_id }}
  BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}        

jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'pr' }}
      model_type: ${{ inputs.model_type || 'london_taxi' }}