name: London Taxi PR Workflow

on:
  pull_request:
    branches:
      - development
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/london_taxi/**'
      - 'model/london_taxi/**'
      - 'src/london_src/**'
      - 'test/london_taxi/**'
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "london_taxi"

jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'pr' }}
      model_type: ${{ inputs.model_type || 'london_taxi' }}
    secrets:
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
      workspace_name: ${{ secrets.WORKSPACE_NAME }}
      # azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure_managed_identity: ${{ secrets.AZURE_MANAGED_IDENTITY }}
