name: Platform PR Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
    secrets:
      subscription_id:
        description: "the subscription ID hosting the AML instance."
        required: true
      resource_group_name:
        description: "the resource group name hosting the AML instance."
        required: true
      workspace_name:
        description: "the workspace name hosting the AML instance."
        required: true
      # azure_credentials:
      #   description: "the credentials to use to authenticate with Azure."
      #   required: true
      azure_managed_identity:
        description: "the managed identity to use to authenticate with Azure."
        required: true        
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
  execute-ml-job-pipeline:
    name: Execute ML Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
    
      - name: Execute AzureML Pipeline
        uses: ./.github/actions/execute_shell_code
        env: 
            SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
            RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
            WORKSPACE_NAME: ${{ secrets.workspace_name }}
            BUILD_BUILDID: ${{ github.run_id }}
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
            # azure_credentials: ${{ secrets.azure_credentials }}
            azure_managed_identity: ${{ secrets.AZURE_MANAGED_IDENTITY }}
            script_parameter: |
                python -m mlops.${{ inputs.model_type }}.src.mlops_pipeline \
                    --build_environment ${{ inputs.exec_environment }} \
                    --wait_for_completion True
